# Working on Real-Time Project with Python on 'Udemy Courses Dataset'

## (A part of Big Data Analysis)

---

# UDEMY COURSES DATASET

---

This dataset contains all course data for all subjects.

We will analyze this data using the Pandas Library.

Here, the quesitons are given for the practice and learning purpose.

---

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('Project+7+-+Udemy+Dataset.csv')
data.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

### 1. What are all different subjects for which Udemy is offering courses ?

In [8]:
data['subject'].unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

In [7]:
data['subject'].value_counts()

subject
Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: count, dtype: int64

### 2. Which subject has the maximum number of courses.

In [9]:
data['subject'].value_counts()

subject
Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: count, dtype: int64

In [11]:
#### Web developmet has the maximum number of courses

### 3. Show all the courses which are Free of Cost.

In [20]:
free_course= data.groupby('is_paid').get_group(False)
free_course['subject']

41      Musical Instruments
49      Musical Instruments
57      Musical Instruments
67          Web Development
74         Business Finance
               ...
3620        Web Development
3638        Web Development
3652        Web Development
3674    Musical Instruments
3680       Business Finance
Name: subject, Length: 310, dtype: object

In [21]:
data[data['is_paid']==False].head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance

### 4. Show all the courses which are Paid.

In [15]:
data[data['is_paid']==True].head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

### 5. Which are Top Selling Courses ?

In [24]:
data.sort_values('num_subscribers', ascending= False).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
1388,19421,Free Beginner Electric Guitar Lessons,False,Free,101154,1042,95,Beginner Level,4.5 hours,2012-06-15T17:00:33Z,Musical Instruments
3556,473160,Web Design for Web Developers: Build Beautiful...,False,Free,98867,6512,20,All Levels,3 hours,2015-04-13T18:29:47Z,Web Development
2233,94430,Learn Javascript & JQuery From Scratch,True,30,84897,2685,10,All Levels,2 hours,2013-10-10T15:19:29Z,Web Development
2886,130064,Practical PHP: Master the Basics and Code Dyna...,False,Free,83737,4598,45,All Levels,6.5 hours,2014-07-19T03:02:05Z,Web Development
2034,364426,JavaScript: Understanding the Weird Parts,True,175,79612,16976,85,All Levels,11.5 hours,2015-03-12T23:19:54Z,Web Development

### 6. Which are Least Selling Courses ?

In [25]:
data.sort_values('num_subscribers', ascending= True).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
1325,1187084,Forex how traders beat the markest with little...,True,100,0,0,16,All Levels,1 hour,2017-07-06T21:16:13Z,Business Finance
2596,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
2597,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
848,1232390,Corporate Ethics,True,100,0,0,13,Beginner Level,3.5 hours,2017-07-03T21:39:13Z,Business Finance
2900,995384,Professional Business Logo Design Using Free O...,True,20,0,0,5,All Levels,37 mins,2016-10-31T16:09:48Z,Graphic Design

### 7. Show all courses of Graphic Design where the price is below 100 ?

In [38]:
data['price'] = pd.to_numeric(data['price'], errors='coerce')
data[(data['subject']=='Graphic Design') & (data['price']<100)]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25.0,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30.0,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20.0,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20.0,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
52,794036,8 Stunden professionelles Cinema 4D Training,True,50.0,18,1,38,All Levels,8.5 hours,2016-03-22T20:51:28Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3568,133968,Web Elements Design With Photoshop,True,45.0,5072,38,44,All Levels,5 hours,2014-10-21T19:18:12Z,Graphic Design
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20.0,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20.0,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30.0,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50.0,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

### 8. List out all the courses that are related with 'Python'.

In [43]:
data[data['course_title'].str.contains('Python')].head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120.0,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195.0,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110.0,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195.0,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,NaN,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development

In [44]:
len(data[data['course_title'].str.contains('Python')])

29

### 9. What are courses that published in year 2015 ?

In [46]:
data['published_timestamp'] = pd.to_datetime(data['published_timestamp'])

In [51]:
(data['published_timestamp']).dtype

datetime64[ns, UTC]

In [59]:
courses_2015 = data[data['published_timestamp'].dt.year == 2015]
courses_2015[['published_timestamp','course_title']]

,published_timestamp,course_title
10,2015-08-30 22:48:34+00:00,1 - Concepts of Statistics For Beginners Step ...
16,2015-03-08 19:11:24+00:00,10 Numbers Every Business Owner Should Know
19,2015-01-04 21:14:31+00:00,101 Blues riffs - learn how the harmonica supe...
23,2015-07-10 19:53:56+00:00,16 Guitar Chords to Jam With - (Beginner - Int...
26,2015-04-27 23:18:59+00:00,2 Easy Steps To Investment And Avoiding Traps
...,...,...
3675,2015-07-16 17:07:49+00:00,Your First Course on Piano
3676,2015-05-26 20:48:48+00:00,Your First Successful Forex Trades - With Case...
3677,2015-04-20 22:15:17+00:00,Your Own Site in 45 Min: The Complete Wordpres...
3678,2015-10-26 20:04:21+00:00,Your Second Course on Piano: Two Handed Playing
3679,2015-11-11 18:55:45+00:00,Zend Framework 2: Learn the PHP framework ZF2 ...

### 10. What are the Max. Number of Subscribers for Each Level of courses ?

In [63]:
data.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [65]:
data.groupby('level').max()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,content_duration,published_timestamp,subject
level,,,,,,,,,,
All Levels,1277924,６時間でインターバンク市場を攻略！最短距離でトレード基礎力,True,200.0,268923,27445,544,9.5 hours,2017-07-06 21:16:13+00:00,Web Development
Beginner Level,1282064,７日でマスター ビギナー向け Adobe Illustrator どきどきセミナー,True,200.0,161029,5924,779,9.5 hours,2017-07-06 21:46:30+00:00,Web Development
Expert Level,1275790,[Value Investing] Where White People Keep Thei...,True,200.0,5172,249,157,9 hours,2017-07-04 18:08:01+00:00,Web Development
Intermediate Level,1276182,株式投資で本当のテクニカル分析ができるようになる,True,200.0,29167,3326,320,9.5 hours,2017-07-05 04:41:54+00:00,Web Development